
if (USE_ORACLEVERSION STREQUAL 12)
  set (ORACLEVERSION 12 CACHE STRING "PyTools version")
elseif (USE_ORACLEVERSION STREQUAL 18)
  set (ORACLEVERSION 18 CACHE STRING "PyTools version")
elseif (USE_ORACLEVERSION STREQUAL 19)
  set (ORACLEVERSION 19 CACHE STRING "PyTools version")
endif ()
